name: data-fetching-test
on: [push, workflow_dispatch]
jobs:
  fetch-today-data:
    name: Fetch Today Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Set Timezone to Bangkok/Thailand
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Bangkok'
      - name : Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}
      - name: Setup Python Requirements
        run : pip install -r requirements.txt
      - name: Fetch Dashboard Data
        working-directory: ./src
        run: |
          python scrape_tableau_data.py
      - name: Build National Timeseries
        working-directory: ./src
        run: |
          python build_national_timeseries.py
      - name: Show scraped data
        run: |
          cat .wiki/dataset/national-timeseries.csv
