name: fetch-today-data
on:
#   schedule:
#     - cron: '30 0 * * *' # 07:30 (UTC+7)
#     - cron: '0 1 * * *' # 08:00 (UTC+7)
#     - cron: '30 1 * * *' # 08:30 (UTC+7)
#     - cron: '0 2 * * *' # 09:00 (UTC+7)
  workflow_dispatch:
jobs:
  fetch-today-data:
    name: Fetch Today Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.2
      - name: Set Timezone to Bangkok/Thailand
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Bangkok'
      - name: Cache Python Environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Setup Python Requirements
        run : pip install -r requirements.txt
      - name: Fetch Dashboard Data
        working-directory: ./src
        env:
          PRODUCTION: 1
        run: |
          python scrape_tableau_data.py
      - name: Build National Timeseries
        working-directory: ./src
        run: |
          python build_national_timeseries.py
      - name: Upload json to wiki
        uses: noppakorn/external-repo-sync-action@v1
        with:
          source-directory: "./wiki"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
